### ISSUE TITLE
k = -k - 1？    

### ISSUE THREAD

**Issue by RuixiangMa** [liumx10/ICPP-RNTree#1]
Hey, that is nice work. However, I'm confused about' k = -k - 1', which means the first number larger than k in your annotation. Can you explain it?

**Comment by liumx10** [comment]
If RNTree does not find a key in the slot array,  it will find a correct position to insert it. Here is a small trick for binary search. The negative number means there is no such key in the array; positive number means the key exists.  Here 'k' is the first position larger than (but not equal) the key, where we should insert the new key.

**Comment by RuixiangMa** [comment]
I  get it, thanks!
